"""empty message

Revision ID: 98360084b4f0
Revises: 93597be558ba
Create Date: 2025-04-19 22:58:45.332469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98360084b4f0'
down_revision = '93597be558ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
